// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: record.pb.proto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Core
{

    [global::ProtoBuf.ProtoContract()]
    public partial class PbCmdData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Code { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsPacked = true)]
        public long[] Args { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PbPlayerFrame : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public ulong PlayerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"CmdList")]
        public global::System.Collections.Generic.List<PbCmdData> CmdLists { get; } = new global::System.Collections.Generic.List<PbCmdData>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PbFrameData : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint FrameNum { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"PlayerList")]
        public global::System.Collections.Generic.List<PbPlayerFrame> PlayerLists { get; } = new global::System.Collections.Generic.List<PbPlayerFrame>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PbRecord : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2)]
        public int MapId { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public uint FrameMs { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public uint FrameNum { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"FrameList")]
        public global::System.Collections.Generic.List<PbFrameData> FrameLists { get; } = new global::System.Collections.Generic.List<PbFrameData>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, CS8981, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
